baseURL: /
languageCode: en-us
title: The Nudge Collaborative
theme: hugo-fresh-mod

params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: The Nudge Unit Collaborative
    # Hero subtitle (optional)
    subtitle: Learn. Share. Improve.
    # Button text
    buttontext: Join Us
    # Where the main hero button links to
    buttonlink: "#section7"
    # Hero image (from /images/___)
    image: illustrations/logos-min.png
    # Footer logos (from /images/logos/clients/___.svg)
    clientlogos:
    - flu
    - Statin
    - generic
    - mm
    - cardiac
    - screening
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Why Nudge?
    url: /#section1
  - title: Leverage Successes
    url: /#section2
  - title: The Collaborative
    url: /#section3
  - title: Platform Features
    url: /#section4
  - title: The Team
    url: /#section6
  - title: Join Us
    url: /#section7
    button: true
  sidebar:
    # Logo (from /images/logos/___.svg)
    logo: fresh-square
    sections:
    - title: User
      icon: user
      links:
      - text: Profile
        url: /
      - text: Account
        url: /
      - text: Settings
        url: /
    - title: Messages
      icon: envelope
      links:
      - text: Inbox
        url: /
      - text: Compose
        url: /
    - title: Images
      icon: image
      links:
      - text: Library
        url: /
      - text: Upload
        url: /
    - title: Settings
      icon: cog
      links:
      - text: User settings
        url: /
      - text: App settings
        url: /
  section1:
    title: Why Nudge?
    subtitle: Nudges can be very effective, but only if well-designed
    tiles:
    - title: Generic Rx
      icon: Generic
      text: Patient & Provider Targeting <br> Set EHR Default Options
      url: /
      buttonText: 
    - title: Statin Rx
      icon: Statin
      text: Active Choice Framing <br> Peer Comparison Feedback
      url: /
      buttonText: 
    - title: Flu Vaccination
      icon: Syringe
      text: Patient & Provider Targeting <br> Active Choice EHR Prompts
      url: /
      buttonText:
    tiles2: 
    - title: Cancer Screening
      icon: Colon
      text: Patient & Provider Targeting <br> Active Choice EHR Prompts
      url: /
      buttonText: 
    - title: Opioid Rx
      icon: Pill
      text: Targeting <br> Set EHR Default Options
      url: /
      buttonText:
    - title: Cardiac Rehab Referral
      icon: Referral
      text: Implement Opt-Out Pathway <br> Being studied
      url: /
      buttonText: 
  section2:
    title: Leverage Successes
    subtitle: Let’s work together to move forward faster
    features:
    - title: Demonstrate Quick Successes
      text: How do you know what problems to target first and which nudges are more likely to work? Hit the ground running by leveraging evidence generated by your peers. Reduce your upfront cost and increase your chances of success
      icon: money
    - title: Behavioral Economic Guidance
      text: Don’t have experts in behavioral economics at your institution? Don’t worry, we’ve got you covered. Learn from leaders in the field
      icon: be2
    - title: Translating Guidelines to Implementation
      text: Guidelines are a consensus of evidence and expert opinion, but implementing nudges in health care means these recommendations need to be translated to EHR codes and language. Save time by using the code implemented by your peers and make it better by contributing your work
      icon: impl
    - title: Automated Statistical Analysis
      text: Analyzing clinical data can be complicated and tedious. What if you could upload your data and at the push of a button analyze clinical outcomes and isolate outlier practices or clinicians?
      icon: Analytics
    # - title: Benchmarking & Research
    #   text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
    #   icon: Seo
  section3:
    title: The Collaborative
    subtitle: Shared continuous improvement
    tiles:
    - title: Join A Community
      icon: Add
      text: Membership fees will be invested in the platform for mutual benefit
      url: /
      buttonText:
    - title: Ask The Experts
      icon: Compass
      text: Hit a roadblock? Ask an expert who has been through this before
      url: /
      buttonText: 
    - title: Stimulate New Research
      icon: Think
      text: We’ll learn more working together. De-identified data will be available for research
      url: /
      buttonText: 
    tiles2:
    - title: Ready to Implement
      icon: Gift
      text: Not sure where to start? Get codes and guidance on nudges demonstrated to work
      url: /
    - title: Benchmarking
      icon: Seo
      text: How do you compare to peer institutions? Share your data and see how you can improve
      url: /
      buttonText: 
    - title: Automated Analysis
      icon: Analytics
      text: No statistician or programmer necessary. Run analyses at the push of a button 
      url: /
      buttonText: 
  section4: 
    title: Platform Features
    subtitle: Codifying Shared Knowledge
    features:
    - title: Library
      text: A growing database of successful and unsuccessful nudges of all types. For each, get access to all associated evidence based changes made - EHR changes, data extracts, code consolidation, analysis and more. 
      icon: Library
    - title: Guides & Code
      text: Step-by-step guidance on how to implement a nudge from start to finish. Templated pitch decks to get buy-in from a range of audiences including executive leadership and clinicians at the frontlines of care
      icon: Code
    - title: Data For Research
      text: De-identified data is available for all members to conduct research to help grow insights generated by the community
      icon: Unlock
    - title: Benchmarking 
      text: Members are required to submit benchmarking data. The Collaborative can do anonymization and more for you or you can do it yourself
      icon: Performance
    - title: Contributions Welcome 
      text: Each organization has its own EHR. We welcome, encourage and will actively support any contributions. All code contributions are shared with the community
      icon: OpenSource
  section5:
    title: Contact us for a demo
    subtitle: ICYMI
    image: illustrations/mockups/mockup2-min.png
    buttonText: 
    buttonLink: "#"
  section6:
    title: The Team
    subtitle: We've launched and grown institutes, units, centers and software companies
    clients:
    - name: David Asch, MD, MBA
      quote: David Asch is the executive director of the Penn Medicine Center for Health Care Innovation. He is the John Morgan professor of medicine and medical ethics and health policy at the Perelman School of Medicine, and a professor of health care management and operations, information and decisions at the Wharton School
      job: Executive Director, Center for Health Care Innovation
      img: asch-min
      link: https://healthcareinnovation.upenn.edu/bio/david-asch-md-mba
    - name: Mohan Balachandran, MA, MS
      quote: Mohan Balachandran serves as the chief operating officer for the Way to Health platform at the Penn Medicine Center for Health Care Innovation. Before joining Penn, he most recently co-founded Datica to address the two biggest hurdles to innovation in health care−namely, cloud regulatory compliance, and data interoperability. Before founding Datica, he launched Share.md, a physician communication company, and mthSense, a Summer 2012 YCombinator mobile advertising company
      job: Corporate Director, PennMed
      img: mohan-min
      link: https://healthcareinnovation.upenn.edu/bio/mohan-balachandran-ma-ms
    - name: Mitesh Patel, MD, MBA, MS
      quote: Mitesh is the director of the Penn Medicine Nudge Unit, a faculty member at the Penn Medicine Center for Health Care Innovation and the Center for Health Incentives and Behavioral Economics, and a staff physician at the Philadelphia VA Medical Center.  Mitesh is also an assistant professor of medicine at the Perelman School of Medicine and an assistant professor of health care management at the Wharton School at the University of Pennsylvania
      job: Director, Nudge Unit
      img: mitesh-min
      link: https://healthcareinnovation.upenn.edu/bio/mitesh-patel-md-mba-ms
    - name: Kevin Volpp, MD, PhD
      quote: Kevin Volpp is the founding director of the Center for Health Incentives and Behavioral Economics at the Leonard Davis Institute (CHIBE) and the Founders President's Distinguished Professor at the Perelman School of Medicine and the Wharton School.  He is also a board-certified practicing physician at the Philadelphia VAMC
      job: Founding Director, CHIBE. Co-Director, CHCI
      img: volpp-min
      link: https://healthcareinnovation.upenn.edu/bio/kevin-volpp-md-phd
  footer:
    # Logo (from /images/logos/___)
    logo: nc.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://pennmedicine.org
      icon: pennnn.png
    - link: http://nudgeunit.upenn.edu/
      icon: nudge_logo_0.png
    - link: https://healthcareinnovation.upenn.edu/
      icon: chci2.png
    - link: https://chibe.upenn.edu/
      icon: chibe2.png
    - link: http://waytohealth.org/
      icon: waytohealth2.png
    bulmalogo: false
    product:
    - text: Discover features
      link: /
    - text: Why choose our product?
      link: /
    - text: Compare features
      link: /
    - text: Our roadmap
      link: /
    - text: Request features
      link: /
    docs:
    - text: 
      link: /
    - text: User guides
      link: /
    - text: Admin guide
      link: /
    - text: Developers
      link: /
    blogroll:
    - text: Latest news
      link: /
    - text: Tech articles
      link: /
    - text: Video blog
      link: /